using TMPro;
using UnityEngine;

/// <summary>
/// A number that floats up off whatever was just hit and fades out.
///
/// Built in code with a world-space TextMeshPro rather than a canvas, so it needs no
/// prefab and no scene setup — and it survives the map scene being regenerated by
/// the editor script, which strips hand-built canvases.
/// </summary>
public class DamageNumber : MonoBehaviour
{
    private const float RiseSpeed = 1.6f;
    private const float Lifetime  = 0.9f;

    private TMP_Text _label;
    private float    _bornAt;
    private Color    _baseColor;

    /// <summary>Colours for the two directions damage travels.</summary>
    public static readonly Color PlayerDealt = new(1.00f, 0.86f, 0.35f);
    public static readonly Color PlayerTook  = new(0.95f, 0.30f, 0.30f);
    public static readonly Color Healed      = new(0.35f, 0.90f, 0.45f);

    /// <summary>
    /// A critical hit. Deliberately far from the ordinary damage colour — a crit that
    /// looks like a slightly brighter normal hit is a stat the player cannot see
    /// working, and critical chance is meant to be felt.
    ///
    /// GREEN, and bigger. It was orange, which sat close enough to the ordinary
    /// yellow that a crit read as a slightly better hit rather than as an event.
    /// Colour alone was doing all the work; size now carries most of it, which also
    /// means a crit is legible to somebody who cannot separate the two hues.
    /// </summary>
    public static readonly Color PlayerCrit  = new(0.30f, 1.00f, 0.35f);

    /// <summary>How much larger a critical hit draws. See PlayerCrit.</summary>
    public const float CritScale = 1.85f;

    private const float BaseFontSize = 4f;

    /// <summary>
    /// How far above a target's origin a number appears.
    ///
    /// Origins are at the feet. Two and a half clears a standing character without
    /// reaching the name plate above it.
    /// </summary>
    private const float HeightAboveTarget = 2.5f;

    /// <summary>
    /// Spawns a number above a point. Amounts below 1 are skipped — a stream of "0"s
    /// over a heavily armoured target is noise, not feedback.
    /// </summary>
    public static void Spawn(Vector3 worldPosition, double amount, Color color, string prefix = "")
        => Spawn(worldPosition, amount, color, prefix, big: false);

    /// <summary>
    /// As above, and larger when it mattered.
    ///
    /// The size is passed rather than inferred from the colour, because the colour is
    /// the caller's choice and a future one that happens to be green should not
    /// silently start drawing double-height numbers.
    /// </summary>
    public static void Spawn(Vector3 worldPosition, double amount, Color color, string prefix, bool big)
    {
        if (amount < 1d) return;

        var go = new GameObject("DamageNumber");

        // Slight horizontal scatter so simultaneous hits do not stack into one
        // unreadable smear.
        Vector3 jitter = new(Random.Range(-0.35f, 0.35f), 0f, Random.Range(-0.2f, 0.2f));

        // ══ ABOVE THE HEAD, NOT THROUGH THE CHEST ═════════════════════════════
        //
        // A SPUM rig's origin is at its feet and the art is roughly two units tall, so
        // 1.8 put the number squarely across the character -- which is exactly where
        // the sprite is, and the two fought for the same pixels.
        //
        // Clear of the head and below the name plate, so a hit and a name are never
        // the same line of text.
        go.transform.position = worldPosition + Vector3.up * HeightAboveTarget + jitter;

        var label = go.AddComponent<TextMeshPro>();
        label.text      = prefix + NumberFormatter.Format((long)amount);
        label.fontSize  = big ? BaseFontSize * CritScale : BaseFontSize;
        label.alignment = TextAlignmentOptions.Center;
        label.color     = color;
        label.GetComponent<RectTransform>().sizeDelta = new Vector2(6f, 1.5f);

        // Reuse the existing billboard so the text always faces the camera, which
        // matters now that the camera can orbit.
        go.AddComponent<Billboard>();

        var number = go.AddComponent<DamageNumber>();
        number._label     = label;
        number._baseColor = color;
        number._bornAt    = Time.time;

        Destroy(go, Lifetime);
    }

    void Update()
    {
        float age = Time.time - _bornAt;

        transform.position += Vector3.up * (RiseSpeed * Time.deltaTime);

        // Hold full opacity briefly so a fast-fading number is still readable.
        float fade = Mathf.InverseLerp(Lifetime * 0.35f, Lifetime, age);
        if (_label != null)
            _label.color = new Color(_baseColor.r, _baseColor.g, _baseColor.b, 1f - fade);
    }
}
