using TMPro;
using UnityEngine;

/// <summary>
/// The name floating over somebody's head.
///
/// ══ WHY THE COLOUR CARRIES THE MEANING ════════════════════════════════════════
///
/// A name tells you who. The colour tells you what they are to you, at a glance and
/// without reading — which is the only thing that works in a fight, because nobody
/// reads six labels while a goblin is hitting them.
///
/// Three roles, deliberately far apart in hue rather than three shades of one colour:
/// yourself, another player, and something hostile. The distinction that matters most
/// is the last one, so it is the one that looks least like the other two.
///
/// ══ WHY IT IS BUILT IN CODE ═══════════════════════════════════════════════════
///
/// Same reason as DamageNumber and WorldStatusBar: no prefab, no scene setup, and it
/// survives the map scene being regenerated by the editor script, which strips
/// hand-built canvases. A world-space TextMeshPro plus the existing Billboard is the
/// whole thing.
/// </summary>
public class NamePlate : MonoBehaviour
{
    /// <summary>What somebody is to the player looking at them.</summary>
    public enum Role
    {
        Self,
        OtherPlayer,
        Hostile,
    }

    /// <summary>
    /// Your own name. Deliberately the calmest of the three — it sits on screen
    /// permanently and has nothing to warn anybody about.
    /// </summary>
    public static readonly Color SelfColor = new(0.72f, 0.92f, 1.00f);

    /// <summary>Another player. Friendly, and clearly not you.</summary>
    public static readonly Color OtherPlayerColor = new(0.55f, 1.00f, 0.62f);

    /// <summary>Something that will hit you.</summary>
    public static readonly Color HostileColor = new(1.00f, 0.42f, 0.38f);

    private const float FontSize = 2.6f;

    /// <summary>
    /// Above the health bar rather than sharing its line.
    ///
    /// WorldStatusBar attaches at its own height and a name on the same line would
    /// overlap it the moment either one is wider than expected.
    /// </summary>
    public const float DefaultHeight = 3.15f;

    /// <summary>
    /// How thick the black outline is, as a fraction of the glyph.
    ///
    /// A name is drawn over grass, stone, water and whatever colour a monster happens
    /// to be, so no single text colour is readable everywhere. The outline is what
    /// makes it legible against all of them, and it does more work than the fill
    /// colour does.
    /// </summary>
    private const float OutlineWidth = 0.25f;

    /// <summary>
    /// A dark plate behind the glyphs, on top of the outline.
    ///
    /// Belt and braces, and cheap: it is text markup rather than a second renderer,
    /// so it costs no draw call and cannot come apart from the label it belongs to.
    /// </summary>
    private const string Backing = "<mark=#00000099>";

    private TMP_Text _label;

    public static Color ColorFor(Role role) => role switch
    {
        Role.Self        => SelfColor,
        Role.OtherPlayer => OtherPlayerColor,
        _                => HostileColor,
    };

    /// <summary>
    /// Hangs a name over a character, and hands it back so the name can change.
    ///
    /// Returns null for a null host rather than throwing: callers attach these during
    /// spawn, and a spawn that raced a scene unload should not take the map with it.
    /// </summary>
    public static NamePlate Attach(GameObject host, string text, Role role,
                                   float heightAbove = DefaultHeight)
    {
        if (host == null) return null;

        var go = new GameObject("NamePlate");

        go.transform.SetParent(host.transform, false);
        go.transform.localPosition = Vector3.up * heightAbove;

        var label = go.AddComponent<TextMeshPro>();

        label.fontSize  = FontSize;
        label.alignment = TextAlignmentOptions.Center;
        label.color     = ColorFor(role);
        label.text      = Decorate(text);

        // fontMaterial, not fontSharedMaterial: touching the shared one would outline
        // every piece of text in the game that happens to use the same font asset.
        Material material = label.fontMaterial;

        material.EnableKeyword(ShaderUtilities.Keyword_Outline);
        material.SetFloat(ShaderUtilities.ID_OutlineWidth, OutlineWidth);
        material.SetColor(ShaderUtilities.ID_OutlineColor, Color.black);

        // Wide enough for a 20-character name, which is the cap CharacterManager
        // enforces. Narrower and long names wrap onto a second line over the head.
        label.GetComponent<RectTransform>().sizeDelta = new Vector2(8f, 1.2f);

        // ══ THE PLATE IS BILLBOARDED, THE CHARACTER IS MIRRORED ═══════════════
        //
        // SpriteFacing flips the art subtree's scale.x to turn a character around.
        // Anything with glyphs on it under that subtree turns into mirror writing --
        // which is exactly why this parents to the HOST ROOT and carries its own
        // Billboard, and why SpriteFacing.CountMirroredText exists to catch the day
        // somebody parents one to the art instead.
        go.AddComponent<Billboard>();

        var plate = go.AddComponent<NamePlate>();
        plate._label = label;

        return plate;
    }

    public void SetText(string text)
    {
        if (_label != null) _label.text = Decorate(text);
    }

    /// <summary>Wraps a name in its backing plate. Empty stays empty, so a blank draws nothing.</summary>
    private static string Decorate(string text) =>
        string.IsNullOrEmpty(text) ? "" : Backing + text + "</mark>";

    public void SetRole(Role role)
    {
        if (_label != null) _label.color = ColorFor(role);
    }

    public void SetVisible(bool visible)
    {
        if (_label != null) _label.enabled = visible;
    }
}
