using UnityEngine;

/// <summary>
/// Top-level singleton. Bootstraps all other managers, owns the game state machine.
/// Placed on a persistent "Managers" GameObject in the Bootstrap scene.
/// </summary>
public class GameManager : MonoBehaviour
{
    public static GameManager Instance { get; private set; }

    public enum GameState
    {
        Splash,
        Login,
        CharacterSelect,
        CharacterCreate,
        LoadingIntoGame,
        InGame,
        Disconnected
    }

    public GameState CurrentState { get; private set; } = GameState.Splash;

    // ── Manager references (all on the same Managers GameObject) ─────────────
    public static ContentManager    Content     { get; private set; }
    public static AccountManager    Account     { get; private set; }
    public static CharacterManager  Character   { get; private set; }
    public static InventoryManager  Inventory   { get; private set; }
    public static BankManager       Bank        { get; private set; }
    public static EquipmentManager  Equipment   { get; private set; }
    public static SkillManager      Skills      { get; private set; }
    public static ActivityManager   Activity    { get; private set; }
    public static MergeManager      Merge       { get; private set; }
    public static ZoneManager       Zone        { get; private set; }
    public static CollectionManager Collection  { get; private set; }
    public static UIManager         UI          { get; private set; }
    public static AudioManager      Audio       { get; private set; }
    public static GhostSpawner      Ghosts      { get; private set; }

    // ── Stubs (Phase 7+) ──────────────────────────────────────────────────────
    public static AuctionManager    Auction     { get; private set; }
    public static GuildManager      Guild       { get; private set; }
    public static QuestManager      Quests      { get; private set; }
    public static SlayerManager     Slayer      { get; private set; }
    public static SaveManager       Save        { get; private set; }
    public static ShopManager       Shop        { get; private set; }
    public static StatsManager      Stats       { get; private set; }

    void Awake()
    {
        if (Instance != null) { Destroy(gameObject); return; }
        Instance = this;
        DontDestroyOnLoad(gameObject);

        // Collect managers — they're all components on this same GameObject.
        //
        // Adding any that are missing, rather than leaving the static null.
        // Bootstrap.unity is generated by an editor menu item, so a manager added to
        // the code but not yet written into the scene leaves its accessor null — and
        // because every call site is written `GameManager.Shop?.Buy(...)`, the result
        // is a button that does nothing at all, with no error anywhere. That is
        // exactly how the shop appeared to work and granted no coins.
        //
        // A manager is a bare MonoBehaviour holding no scene references, so creating
        // one at runtime is equivalent to having authored it. The scene is still the
        // source of truth; this just stops it being a silent one.
        // ORDER MATTERS when a component has to be created: AddComponent runs Awake
        // immediately, and AccountManager.Awake loads the save through SaveManager.
        // Adding Account before Save would hand a fresh account to anyone whose
        // Bootstrap scene predates SaveManager — i.e. silently wipe their progress.
        Content    = Require<ContentManager>();
        Save       = Require<SaveManager>();
        Account    = Require<AccountManager>();

        Character  = Require<CharacterManager>();
        Inventory  = Require<InventoryManager>();
        Bank       = Require<BankManager>();
        Equipment  = Require<EquipmentManager>();
        Skills     = Require<SkillManager>();
        Activity   = Require<ActivityManager>();
        Merge      = Require<MergeManager>();
        Zone       = Require<ZoneManager>();
        Collection = Require<CollectionManager>();
        UI         = Require<UIManager>();
        Audio      = Require<AudioManager>();
        Ghosts     = Require<GhostSpawner>();
        Auction    = Require<AuctionManager>();
        Guild      = Require<GuildManager>();
        Quests     = Require<QuestManager>();
        Slayer     = Require<SlayerManager>();
        Shop       = Require<ShopManager>();

        // Counts kills as they happen, which nothing did before -- the kill event has
        // fired since it was written and never had a subscriber. No static accessor:
        // it is a listener, not something other code asks questions of, and KillTracker
        // exposes its reads as statics.
        Require<KillTracker>();

        // Last: it reads from equipment, talents and the content catalogue, so every
        // one of those has to exist before its first recompute.
        Stats      = Require<StatsManager>();
    }

    /// <summary>
    /// The manager component, created on this object if the scene did not carry one.
    ///
    /// Says so loudly when it has to: a scene that needs regenerating should be
    /// reported once at startup, not discovered three features later.
    /// </summary>
    private T Require<T>() where T : Component
    {
        var existing = GetComponent<T>();
        if (existing != null) return existing;

        Debug.LogWarning($"[GameManager] Bootstrap.unity has no {typeof(T).Name} — adding one. " +
                         "Run 'Idle Explorers → Setup Everything' to write it into the scene.");
        return gameObject.AddComponent<T>();
    }

    void Start()
    {
        // CurrentState is initialized to Splash but nothing had ever transitioned
        // *to* it, so UIManager never pushed SplashScreen and the first frame was
        // blank. Transition explicitly so the splash is actually shown while
        // content loads.
        TransitionTo(GameState.Splash);

        // Volume / quality / fullscreen chosen in a previous session
        SettingsPanel.ApplySavedSettings();

        // Content loads first (async), then transitions to Login when ready
        if (Content != null)
            Content.LoadAll(OnContentReady);
        else
            TransitionTo(GameState.Login);
    }

    void OnContentReady()
    {
        // Deliberately does not transition. SplashScreen polls Content.IsLoaded and
        // moves to Login itself once its loading bar has played — transitioning here
        // as well would race it and skip the splash entirely.
        Debug.Log("[GameManager] Content ready.");

        // Content-driven systems get one chance to complain about their own data
        // while the console is still readable. A talent with a misspelled effectType
        // costs a point and does nothing, which is otherwise invisible.
        TalentManager.ValidateContent();
    }

    /// <summary>Transition to a new game state. UIManager reacts to show the right screen.</summary>
    public void TransitionTo(GameState newState)
    {
        Debug.Log($"[GameManager] {CurrentState} → {newState}");
        CurrentState = newState;
        UI?.OnStateChanged(newState);
        Audio?.OnStateChanged(newState);
    }

    // ── Convenience transition methods ────────────────────────────────────────

    /// <summary>Map a character spawns into when they have never played before.</summary>
    public const string StartingMapId = "goblin_camp";

    public void GoToCharacterSelect()       => TransitionTo(GameState.CharacterSelect);
    public void GoToCharacterCreate()       => TransitionTo(GameState.CharacterCreate);

    /// <summary>
    /// Enters the world. Loads the character's last map (or the starting map) and
    /// shows the HUD — without the map load, InGame would show a HUD over nothing.
    /// </summary>
    public void GoToGame()
    {
        var character = CharacterManager.Current;
        string mapId  = !string.IsNullOrEmpty(character?.lastMapId) ? character.lastMapId : StartingMapId;

        TransitionTo(GameState.InGame);
        Zone?.EnterMap(mapId);

        if (character == null) return;

        character.lastMapId = mapId;

        // ══ AND THE SERVER IS TOLD ══════════════════════════════════════════
        //
        // last_map_id existed in the schema and was already returned in the roster.
        // Nothing had ever written to it, so every character loaded into the starting
        // map for ever -- including one that had travelled somewhere else a minute
        // earlier and logged out there.
        //
        // Fire and forget: the map is already loading, and a player whose location
        // failed to save has lost nothing they can see. The next map change writes it
        // again.
        _ = IdleExplorers.Backend.ServerState.SaveLocationAsync(mapId);
    }
    public void ReturnToMainMenu()
    {
        Character?.SaveAndDisconnect();   // stamps lastLogoutUnixTime and persists
        Zone?.UnloadCurrentZone();
        TransitionTo(GameState.CharacterSelect);
        GameEvents.OnReturnToMainMenu?.Invoke();
    }
}
